#include<stdio.h>
#include<stdlib.h>
#define pf printf
void periodic();
void periodic_table();
int main(void)
{
	int ch1;
	pf("\n\n\n\t\t\t\t*****************WELCOME****************\n");
	pf("\n\n\t\t\t\t\t1. SEARCH ELEMENT\n");
	pf("\n\n\t\t\t\t\t2. VIEW PERIODIC TABLE\n\n\n");
	pf("\n\n\n\n\t\t\t\t\t\t\tENTER YOUR CHOICE: ");
	scanf("%d",&ch1);
	switch(ch1)
	{
	case 1:	periodic();
	break;
	case 2: periodic_table();
	break;
	}
	return 0;
}
void periodic()
{
	int at;
	do
	{
		pf("\n\n\n\t\t\t\tENTER THE ATOMIC NUMBER OF ELEMENT: ");
		scanf("%d",&at);
		pf("\n\n\n");
		switch (at)
		{
			case 57:	pf("NAME= LANTHANUM\nSYMBOL= La\nCLASSIFICATION= LANTHANOIDS\nATOMIC NUMBER= 57\nATOMIC WEIGHT= 138.90547 (g/mol)\nMELTING POINT= 1193.15 K\nBOILLING POINT= 3727.15 K\nELECTRONEGATIVITY= 1.1\n");
			break;
			case 58:	pf("NAME= CERIUM\nSYMBOL= Ce\nCLASSIFICATION= LANTHANOIDS\nATOMIC NUMBER= 58\nATOMIC WEIGHT= 140.116 (g/mol)\nMELTING POINT= 1071.15 K\nBOILLING POINT= 3716.15 K\nELECTRONEGATIVITY= 1.12\n");
			break;
			case 59:	pf("NAME= PRASEODYMIUM\nSYMBOL= Pr\nCLASSIFICATION= LANTHANOIDS\nATOMIC NUMBER= 59\nATOMIC WEIGHT= 140.90465 (g/mol)\nMELTING POINT= 1204.15 K\nBOILLING POINT= 3563.15 K\nELECTRONEGATIVITY= 1.13\n");
			break;
			case 60:	pf("NAME= NEODYMIUM\nSYMBOL= Nd\nCLASSIFICATION= LANTHANOIDS\nATOMIC NUMBER= 60\nATOMIC WEIGHT= 144.242 (g/mol)\nMELTING POINT= 1283.15 K\nBOILLING POINT= 3339.15 K\nELECTRONEGATIVITY= 1.14\n");
			break;
			case 61:	pf("NAME= PROMETHIUM\nSYMBOL= Pm\nCLASSIFICATION= LANTHANOIDS\nATOMIC NUMBER= 61\nATOMIC WEIGHT= 146.9151 (g/mol)\nMELTING POINT= 1439.15 K\nBOILLING POINT= 3271.15 K\nELECTRONEGATIVITY= --\n");
			break;
			case 62:	pf("NAME= SAMARIUM\nSYMBOL= Sm\nCLASSIFICATION= LANTHANOIDS\nATOMIC NUMBER= 62\nATOMIC WEIGHT= 150.36 (g/mol)\nMELTING POINT= 1345.15 K\nBOILLING POINT= 2051.15 K\nELECTRONEGATIVITY= 1.17\n");
			break;
			case 63:	pf("NAME= EUROPIUM\nSYMBOL= Eu\nCLASSIFICATION= LANTHANOIDS\nATOMIC NUMBER= 63\nATOMIC WEIGHT= 151.964 (g/mol)\nMELTING POINT= 1095.15K\nBOILLING POINT= 1870.15 K\nELECTRONEGATIVITY= -- \n");
			break;
			case 64:	pf("NAME= GADOLINIUM\nSYMBOL= Gd\nCLASSIFICATION= LANTHANOIDS\nATOMIC NUMBER= 64\nATOMIC WEIGHT= 157.25 (g/mol)\nMELTING POINT= 1584.15 K\nBOILLING POINT= 3537.15 K\nELECTRONEGATIVITY= 1.2\n");
			break;
			case 65:	pf("NAME= TERBIUM\nSYMBOL= Tb\nCLASSIFICATION= LANTHANOIDS\nATOMIC NUMBER= 65\nATOMIC WEIGHT= 158.9253 (g/mol)\nMELTING POINT= 1633.15 K\nBOILLING POINT= 3294.15 K\nELECTRONEGATIVITY= --\n");
			break;
			case 66:	pf("NAME= DYSPROSIUM\nSYMBOL= Dy\nCLASSIFICATION= LANTHANOIDS\nATOMIC NUMBER= 66\nATOMIC WEIGHT= 162.500 (g/mol)\nMELTING POINT= 1682.15 K\nBOILLING POINT= 2833.15K\nELECTRONEGATIVITY= 1.22\n");
			break;
			case 67:	pf("NAME= HOLMIUM\nSYMBOL= Ho\nCLASSIFICATION= LANTHANOIDS\nATOMIC NUMBER= 67\nATOMIC WEIGHT= 164.9303 (g/mol)\nMELTING POINT= 1743.15 K\nBOILLING POINT= 2966.15 K\nELECTRONEGATIVITY= 1.23\n");
			break;
			case 68:	pf("NAME= ERBIUM\nSYMBOL= Er\nCLASSIFICATION= LANTHANOIDS\nATOMIC NUMBER= 68\nATOMIC WEIGHT= 167.253 (g/mol)\nMELTING POINT= 1795.15 K\nBOILLING POINT= 3134.15 K\nELECTRONEGATIVITY= 1.24\n");
			break;
			case 69:	pf("NAME= THULIUM\nSYMBOL= Tm\nCLASSIFICATION= LANTHANOIDS\nATOMIC NUMBER= 69\nATOMIC WEIGHT= 168.9321 (g/mol)\nMELTING POINT= 1818.15 K\nBOILLING POINT= 2218.15 K\nELECTRONEGATIVITY= 1.25\n");
			break;
			case 70:	pf("NAME= YTTERBIUM\nSYMBOL= Yb\nCLASSIFICATION= LANTHANOIDS\nATOMIC NUMBER= 70\nATOMIC WEIGHT= 173.04 (g/mol)\nMELTING POINT= 1097.15 K\nBOILLING POINT= 1466.15 K\nELECTRONEGATIVITY= --\n");
			break;
			case 71:	pf("NAME= LUTETIUM\nSYMBOL= Lu\nATOMIC NUMBER= 71\nCLASSIFICATION= LANTHANOIDS\nATOMIC WEIGHT= 174.967 (g/mol)\nMELTING POINT= 1929.15 K\nBOILLING POINT= 3666.15 K\nELECTRONEGATIVITY= 1.27\n");
			break;
			case 72:	pf("NAME= HAFNIUM\nSYMBOL= Hf\nCLASSIFICATION= TRANSITION METALS\nATOMIC NUMBER= 72\nATOMIC WEIGHT= 178.49 (g/mol)\nMELTING POINT= 2506.15 K\nBOILLING POINT= 4876.15 K\nELECTRONEGATIVITY= 1.3\n");
			break;
			case 73:	pf("NAME= TANTALUM\nSYMBOL= Ta\nCLASSIFICATION= TRANSITION METALS\nATOMIC NUMBER= 73\nATOMIC WEIGHT= 180.9479 (g/mol)\nMELTING POINT= 3290.15 K\nBOILLING POINT= 5731.15 K\nELECTRONEGATIVITY= 1.5\n");
			break;
			case 74:	pf("NAME= TUNGSTEN\nSYMBOL= W\nCLASSIFICATION= TRANSITION METALS\nATOMIC NUMBER= 74\nATOMIC WEIGHT= 183.84 (g/mol)\nMELTING POINT= 3680.15 K\nBOILLING POINT= 5828.15 K\nELECTRONEGATIVITY= 2.36\n");
			break;
			case 75:	pf("NAME= RHENIUM\nSYMBOL= Re\nCLASSIFICATION= TRANSITION METALS\nATOMIC NUMBER= 75\nATOMIC WEIGHT= 186.207 (g/mol)\nMELTING POINT= 3453.15 K\nBOILLING POINT= 5869.15 K\nELECTRONEGATIVITY= 1.9\n");
			break;
			case 76:	pf("NAME= OSMIUM\nSYMBOL= Os\nCLASSIFICATION= TRANSITION METALS\nATOMIC NUMBER= 76\nATOMIC WEIGHT= 190.23 (g/mol)\nMELTING POINT= 3318.15 K\nBOILLING POINT= 5300.15 K\nELECTRONEGATIVITY= 2.2\n");
			break;
			case 77:	pf("NAME= IRIDIUM\nSYMBOL= Ir\nCLASSIFICATION= TRANSITION METALS\nATOMIC NUMBER= 77\nATOMIC WEIGHT= 192.217 (g/mol)\nMELTING POINT= 2683.15 K\nBOILLING POINT= 4701.15 K\nELECTRONEGATIVITY= 2.2\n");
			break;
			case 78:	pf("NAME= PLATINUM\nSYMBOL= Pt\nCLASSIFICATION= TRANSITION METALS\nATOMIC NUMBER= 78\nATOMIC WEIGHT= 195.084 (g/mol)\nMELTING POINT= 2045.15 K\nBOILLING POINT= 4100.15 K\nELECTRONEGATIVITY= 2.28\n");
			break;
			case 79:	pf("NAME= GOLD\nSYMBOL= Au\nCLASSIFICATION= TRANSITION METALS\nATOMIC NUMBER= 79\nATOMIC WEIGHT= 196.966 (g/mol)\nMELTING POINT= 1337.55 K\nBOILLING POINT= 3129.15 K\nELECTRONEGATIVITY= 2.54\n");
			break;
			case 80:	pf("NAME= MERCURY\nSYMBOL= Hg\nCLASSIFICATION= TRANSITION METALS\nATOMIC NUMBER= 80\nATOMIC WEIGHT= 200.59 (g/mol)\nMELTING POINT= 234.25 K\nBOILLING POINT= 629.75 K\nELECTRONEGATIVITY= 2\n");
			break;
			case 81:	pf("NAME= THALLIUM\nSYMBOL= Tl\nCLASSIFICATION= TRANSITION METALS\nATOMIC NUMBER= 81\nATOMIC WEIGHT= 204.3833 (g/mol)\nMELTING POINT= 576.75 K\nBOILLING POINT= 1746.15 K\nELECTRONEGATIVITY= 1.62\n");
			break;
			case 82:	pf("NAME= LEAD\nSYMBOL= Pb\nCLASSIFICATION= TRANSITION METALS\nATOMIC NUMBER= 82\nATOMIC WEIGHT= 207.2 (g/mol)\nMELTING POINT= 600.65 K\nBOILLING POINT= 2013.15 K\nELECTRONEGATIVITY= 2.33\n");
			break;
			case 83:	pf("NAME= BISMUTH\nSYMBOL= Bi\nCLASSIFICATION= TRANSITION METALS & RADIOACTIVE\nATOMIC NUMBER= 83\nATOMIC WEIGHT= 208.9804 (g/mol)\nMELTING POINT= 544.65 K\nBOILLING POINT= 1833.15 K\nELECTRONEGATIVITY= 2.02\n");
			break;
			case 84:	pf("NAME= POLONIUM\nSYMBOL= Po\nCLASSIFICATION= METALLOID & RADIOACTIVE\nATOMIC NUMBER= 84\nATOMIC WEIGHT= 208.9824 (g/mol)\nMELTING POINT= 527.15 K\nBOILLING POINT= 1235.15 K\nELECTRONEGATIVITY= 2\n");
			break;
			case 85:	pf("NAME= ASTATINE\nSYMBOL= At\nCLASSIFICATION= HALOGEN & RADIOACTIVE\nATOMIC NUMBER= 85\nATOMIC WEIGHT= 209.9871 (g/mol)\nMELTING POINT= 503.15 K\nBOILLING POINT= 575.15 K\nELECTRONEGATIVITY= 2.2\n");
			break;
			case 86:	pf("NAME= RADON\nSYMBOL= Rn\nCLASSIFICATION= NOBLE GASES & RADIOACTIVE\nATOMIC NUMBER= 86\nATOMIC WEIGHT= 222.0176 (g/mol)\nMELTING POINT= 202.15 K\nBOILLING POINT= 211.35 K\nELECTRONEGATIVITY= --\n");
			break;
			case 87:	pf("NAME= FRANCIUM\nSYMBOL= Fr\nCLASSIFICATION= ALKALI METAL & RADIOACTIVE\nATOMIC NUMBER= 87\nATOMIC WEIGHT= 223.0197 (g/mol)\nMELTING POINT= 293.15 K\nBOILLING POINT= 923.15 K\nELECTRONEGATIVITY= --\n");
			break;
			case 88:	pf("NAME= RADIUM\nSYMBOL= Ra\nCLASSIFICATION= ALKALINE EARTH METAL & RADIOACTIVE\nATOMIC NUMBER= 88\nATOMIC WEIGHT= 226.0254 (g/mol)\nMELTING POINT= 1231.15 K\nBOILLING POINT= 2008.15 K\nELECTRONEGATIVITY= --\n");
			break;
			case 89:	pf("NAME= ACTINIUM\nSYMBOL= Ac\nCLASSIFICATION= ACTINOIDS & RADIOACTIVE\nATOMIC NUMBER= 89\nATOMIC WEIGHT= 227.0278 (g/mol)\nMELTING POINT= 1320.15 K\nBOILLING POINT= 3470.15 K\nELECTRONEGATIVITY= 1.1\n");
			break;
			case 90:	pf("NAME= THORIUM\nSYMBOL= Th\nCLASSIFICATION= ACTINOIDS & RADIOACTIVE\nATOMIC NUMBER= 90\nATOMIC WEIGHT= 232.03806 (g/mol)\nMELTING POINT= 20323.15 K\nBOILLING POINT= 5060.15 K\nELECTRONEGATIVITY= 1.3\n");
			break;
			case 91:	pf("NAME= PROTACTINIUM\nSYMBOL= Pa\nCLASSIFICATION= ACTINOIDS & RADIOACTIVE\nATOMIC NUMBER= 91\nATOMIC WEIGHT= 231.03588 (g/mol)\nMELTING POINT= 2113.15 K\nBOILLING POINT= 4303.15 K\nELECTRONEGATIVITY= 1.5\n");
			break;
			case 92:	pf("NAME= URANIUM\nSYMBOL= U\nCLASSIFICATION= ACTINOIDS & RADIOACTIVE\nATOMIC NUMBER= 92\nATOMIC WEIGHT= 238.0289 (g/mol)\nMELTING POINT= 1405.55 K\nBOILLING POINT= 4016.5 K\nELECTRONEGATIVITY= 1.38\n");
			break;
			case 93:	pf("NAME= NEPTUNIUM\nSYMBOL= Np\nCLASSIFICATION= ACTINOIDS & RADIOACTIVE\nATOMIC NUMBER= 93\nATOMIC WEIGHT= 237.0482 (g/mol)\nMELTING POINT= 913.15 K\nBOILLING POINT= 4173.15 K\nELECTRONEGATIVITY= 1.36\n");
			break;
			case 94:	pf("NAME= PLUTONIUM\nSYMBOL= Pu\nCLASSIFICATION= ACTINOIDS & RADIOACTIVE\nATOMIC NUMBER= 94\nATOMIC WEIGHT= 244.0642 (g/mol)\nMELTING POINT= 914.15 K\nBOILLING POINT= 3508.15 K\nELECTRONEGATIVITY= 1.28\n");
			break;
			case 95:	pf("NAME= AMERICIUM\nSYMBOL= Am\nCLASSIFICATION= ACTINOIDS & RADIOACTIVE\nATOMIC NUMBER= 95\nATOMIC WEIGHT= 243.0614 (g/mol)\nMELTING POINT= 1449.15 K\nBOILLING POINT= \nELECTRONEGATIVITY= 1.3\n");
			break;
			case 96:	pf("NAME= CURIUM\nSYMBOL= Cm\nCLASSIFICATION= ACTINOIDS & RADIOACTIVE\nATOMIC NUMBER= 96\nATOMIC WEIGHT= 247.0703 (g/mol)\nMELTING POINT= 1613.15 K\nBOILLING POINT= 3381.15 K\nELECTRONEGATIVITY= 1.3\n");
			break;
			case 97:	pf("NAME= BERKELIUM\nSYMBOL= Bk\nCLASSIFICATION= ACTINOIDS & RADIOACTIVE\nATOMIC NUMBER= 97\nATOMIC WEIGHT= 247.0703 (g/mol)\nMELTING POINT= 1259.15 K\nBOILLING POINT= 2898.15 K\nELECTRONEGATIVITY= 1.33\n");
			break;
			case 98:	pf("NAME= CALIFORNIUM\nSYMBOL= Cf\nCLASSIFICATION= ACTINOIDS & RADIOACTIVE\nATOMIC NUMBER= 98\nATOMIC WEIGHT= 251.0796 (g/mol)\nMELTING POINT= 1173.15 K\nBOILLING POINT= 1743.15 K\nELECTRONEGATIVITY= 1.3\n");
			break;
			case 99:	pf("NAME= EINSTEINIUM\nSYMBOL= Es\nCLASSIFICATION= ACTINOIDS & RADIOACTIVE\nATOMIC NUMBER= 99\nATOMIC WEIGHT= 252.0829 (g/mol)\nMELTING POINT= 1133.15 K\nBOILLING POINT= --\nELECTRONEGATIVITY= 1.3\n");
			break;
			case 100:	pf("NAME= FERMIIM\nSYMBOL= Fm\nCLASSIFICATION= ACTINOIDS & RADIOACTIVE\nATOMIC NUMBER= 100\nATOMIC WEIGHT= 257.0951 (g/mol)\nMELTING POINT= 1798.15 K\nBOILLING POINT= --\nELECTRONEGATIVITY= 1.3\n");
			break;
			case 101:	pf("NAME= MENDELEVIUM\nSYMBOL= Md\nCLASSIFICATION= ACTINOIDS & RADIOACTIVE\nATOMIC NUMBER= 101\nATOMIC WEIGHT= 258.0951 (g/mol)\nMELTING POINT= 1098.15 K\nBOILLING POINT= --\nELECTRONEGATIVITY= 1.3\n");
			break;
			case 102:	pf("NAME= NOBELIUM\nSYMBOL= Nb\nCLASSIFICATION= ACTINOIDS & RADIOACTIVE\nATOMIC NUMBER= 102\nATOMIC WEIGHT= 259.1009 (g/mol)\nMELTING POINT= 1098.15 K\nBOILLING POINT= --\nELECTRONEGATIVITY= 1.3\n");
			break;
			case 103:	pf("NAME= LAWRENCIUM\nSYMBOL= Lr\nCLASSIFICATION= ACTINOIDS & RADIOACTIVE\nATOMIC NUMBER= 103\nATOMIC WEIGHT= 262 (g/mol)\nMELTING POINT= 1898.15 K\nBOILLING POINT= --\nELECTRONEGATIVITY= --\n");
			break;
			case 104:	pf("NAME= RUTHERFORDIUM\nSYMBOL= Rf\nCLASSIFICATION= TRANSITION METALS & RADIOACTIVE\nATOMIC NUMBER= 104\nATOMIC WEIGHT= 267 (g/mol)\nMELTING POINT= --\nBOILLING POINT= --\nELECTRONEGATIVITY= --\n");
			break;
			case 105:	pf("NAME= DUBNIUM\nSYMBOL= Db\nCLASSIFICATION= TRANSITION METALS & RADIOACTIVE\nATOMIC NUMBER= 105\nATOMIC WEIGHT= 268 (g/mol)\nMELTING POINT= --\nBOILLING POINT= --\nELECTRONEGATIVITY= --\n");
			break;
			case 106:	pf("NAME= SEABORGIUM\nSYMBOL= Sg\nCLASSIFICATION= TRANSITION METALS & RADIOACTIVE\nATOMIC NUMBER= 106\nATOMIC WEIGHT= 271 (g/mol)\nMELTING POINT= --\nBOILLING POINT= --\nELECTRONEGATIVITY= --\n");
			break;
			case 107:	pf("NAME= BOHRIUM\nSYMBOL= Bh\nCLASSIFICATION= TRANSITION METALS & RADIOACTIVE\nATOMIC NUMBER= 107\nATOMIC WEIGHT= 270 (g/mol)\nMELTING POINT= --\nBOILLING POINT= --\nELECTRONEGATIVITY= --\n");
			break;
			case 108:	pf("NAME= HASSIUM\nSYMBOL= Hs\nCLASSIFICATION= TRANSITION METALS & RADIOACTIVE\nATOMIC NUMBER= 108\nATOMIC WEIGHT= 269 (g/mol)\nMELTING POINT= --\nBOILLING POINT= --\nELECTRONEGATIVITY= --\n");
			break;
			case 109:	pf("NAME= MEITNERIUM\nSYMBOL= Mt\nCLASSIFICATION= TRANSITION METALS & RADIOACTIVE\nATOMIC NUMBER= 109\nATOMIC WEIGHT= 278 (g/mol)\nMELTING POINT= --\nBOILLING POINT= --\nELECTRONEGATIVITY= --\n");
			break;
			case 110:	pf("NAME= DARMSTADTIUM\nSYMBOL= Ds\nCLASSIFICATION= TRANSITION METALS & RADIOACTIVE\nATOMIC NUMBER= 110\nATOMIC WEIGHT= 281 (g/mol)\nMELTING POINT= --\nBOILLING POINT= --\nELECTRONEGATIVITY= --\n");
			break;
			case 111:	pf("NAME= ROENTGENIUM\nSYMBOL= Rg\nCLASSIFICATION= TRANSITION METALS & RADIOACTIVE\nATOMIC NUMBER= 111\nATOMIC WEIGHT= 281 (g/mol)\nMELTING POINT= --\nBOILLING POINT= --\nELECTRONEGATIVITY= --\n");
			break;
			case 112:	pf("NAME= COPERNECIUM\nSYMBOL= Cn\nCLASSIFICATION= TRANSITION METALS & RADIOACTIVE\nATOMIC NUMBER= 112\nATOMIC WEIGHT= 285 (g/mol)\nMELTING POINT= --\nBOILLING POINT= --\nELECTRONEGATIVITY= --\n");
			break;
			case 113:	pf("NAME= NIHONIUM\nSYMBOL= Nh\nCLASSIFICATION= TRANSITION METALS & RADIOACTIVE\nATOMIC NUMBER= 113\nATOMIC WEIGHT= 284 (g/mol)\nMELTING POINT= 698.15 K\nBOILLING POINT= 1428.15 K\nELECTRONEGATIVITY= --\n");
			break;
			case 114:	pf("NAME= FLEROVIUM\nSYMBOL= Fl\nCLASSIFICATION= TRANSITION METALS & RADIOACTIVE\nATOMIC NUMBER= 114\nATOMIC WEIGHT= 289 (g/mol)\nMELTING POINT= --\nBOILLING POINT= --\nELECTRONEGATIVITY= --\n");
			break;
			case 115:	pf("NAME= MOSCOVIUM\nSYMBOL= Mc\nCLASSIFICATION= TRANSITION METALS & RADIOACTIVE\nATOMIC NUMBER= 115\nATOMIC WEIGHT= 289 (g/mol)\nMELTING POINT= --\nBOILLING POINT= --\nELECTRONEGATIVITY= --\n");
			break;
			case 116:	pf("NAME= LIVERMORIUM\nSYMBOL= Lv\nCLASSIFICATION= TRANSITION METALS & RADIOACTIVE\nATOMIC NUMBER= 116\nATOMIC WEIGHT= 292 (g/mol)\nMELTING POINT= --\nBOILLING POINT= --\nELECTRONEGATIVITY= --\n");
			break;
			case 117:	pf("NAME= TENNESSINE\nSYMBOL= Ts\nCLASSIFICATION= HALOGENS & RADIOACTIVE\nATOMIC NUMBER= 117\nATOMIC WEIGHT= 294 (g/mol)\nMELTING POINT= --\nBOILLING POINT= --\nELECTRONEGATIVITY= --\n");
			break;
			case 118:	pf("NAME= OGANESSON\nSYMBOL= Og\nCLASSIFICATION= NOBLE GASES & RADIOACTIVE\nATOMIC NUMBER= 118\nATOMIC WEIGHT=294 (g/mol) \nMELTING POINT= --\nBOILLING POINT= 368.15 K\nELECTRONEGATIVITY= --\n");
			break;
			case 119:	pf("NAME=UNUNENNIUM \nSYMBOL= Uue\nCLASSIFICATION= ALKALI METALS\nATOMIC NUMBER= 119\nATOMIC WEIGHT= 316 (g/mol)\nMELTING POINT= --\nBOILLING POINT= --\nELECTRONEGATIVITY= --\n");
			break;
			case 120:	pf("NAME= UNBINILIUM\nSYMBOL= Ubn\nCLASSIFICATION= ALKALINE EARTH NETALS\nATOMIC NUMBER= 120\nATOMIC WEIGHT= 320 (g/mol)\nMELTING POINT= --\nBOILLING POINT= --\nELECTRONEGATIVITY= --\n");
			break;
			case 121:	pf("NAME= UNBIUNIUM\nSYMBOL= Ubu\nCLASSIFICATION= ACTINOIDS\nATOMIC NUMBER= 121\nATOMIC WEIGHT= 320 (g/mol)\nMELTING POINT= --\nBOILLING POINT= --\nELECTRONEGATIVITY= --\n");
			break;
			case 122:	pf("NAME= UNBIBIUM\nSYMBOL= Ubb\nCLASSIFICATION= ACTINOIDS\nATOMIC NUMBER= 122\nATOMIC WEIGHT= 321 (g/mol)\nMELTING POINT= --\nBOILLING POINT= --\nELECTRONEGATIVITY= --\n");
			break;
			case 123:	pf("NAME= UNBITRIUM\nSYMBOL= Ubt\nCLASSIFICATION= ACTINOIDS\nATOMIC NUMBER= 123\nATOMIC WEIGHT= 325 (g/mol)\nMELTING POINT= --\nBOILLING POINT= --\nELECTRONEGATIVITY= --\n");
			break;
			case 124:	pf("NAME= UNBIQUADIUM\nSYMBOL= Ubq\nCLASSIFICATION= ACTINOIDS\nATOMIC NUMBER= 124\nATOMIC WEIGHT= 330 (g/mol)\nMELTING POINT= --\nBOILLING POINT= --\nELECTRONEGATIVITY= --\n");
			break;
			case 125:	pf("NAME= UNBIPENTIUM\nSYMBOL= Ubp\nCLASSIFICATION= ACTINOIDS\nATOMIC NUMBER= 125\nATOMIC WEIGHT= 332 (g/mol)\nMELTING POINT= --\nBOILLING POINT= --\nELECTRONEGATIVITY= --\n");
			break;
			case 126:	pf("NAME= UNBIHEXIUM\nSYMBOL= Ubh\nCLASSIFICATION= ACTINOIDS\nATOMIC NUMBER= 126\nATOMIC WEIGHT= 334 (g/mol)\nMELTING POINT= --\nBOILLING POINT= --\nELECTRONEGATIVITY= --s\n");
			break;
			default:	pf("NO SUCH ELEMENT FOUND!!! TRY AGAIN....\n");
			break;
		}
	}while(!(at>57&&at<126));
}
void periodic_table()
{
	system("clear");
	printf("\t\t\t                          **********************MODERN PERIODIC TABLE***********************\n\n\n");
	printf("\t\t\tH                                                                                                                  He\n");
	printf("\t\t\tLi   Be                                                                          B      C      N      O      F     Ne\n");
	printf("\t\t\tNa   Mg                                                                          Al     Si     P      S      Cl    Ar\n");
	printf("\t\t\tK    Ca   Sc     Ti      V      Cr      Mn     Fe     Co    Ni    Cu     Zn      Ga     Ge     As     Se     Br    Kr\n");
	printf("\t\t\tRb   Sr   Y      Zr      Nb     Mo      Tc     Ru     Rh    Pd    Ag     Cd      In     Sn     Sb     Te     I     Xe\n");
	printf("\t\t\tCs   Ba   La     Hf      Ta     W       Re     Os     Ir    Pt    Au     Hg      Tl     Pb     Bi     Po     At    Rn\n");
	printf("\t\t\tFr   Ra   Ac     Rf      Db     Sg      Bh     Hs     Mt    Ds    Rg     Cn      Uut    Fl    Uup     Lv    Uus   Uuo\n");
	printf("\n\n\n");
	printf("\t\t\t                 La      Ce     Pr      Nd     Pm     Sm    Eu    Gd     Tb      Dy     Ho     Er     Tm     Yb    Lu\n");
	printf("\t\t\t                 Ac      Th     Pa      U      Np     Pu    Am    Cm     Bk      Cf     Es     Fm     Md     No    Lr\n");
	printf("\n\n\n");
	printf("\t\t\t                          **********************************************************************");
	printf("\n\n\n\n\n");
}
